### PR TITLE
java.lang.NullPointerException

### PR DESCRIPTION
**Pull request by ChanakaWeerasinghe**
java.lang.NullPointerException: Attempt to invoke virtual method 'android.net.Uri android.content.Intent.getData()' on a null object reference

### CODE REVIEW

**Review by svetlin-tide — APPROVED** [review]

**Review by VladimirGradev — APPROVED** [review]

**Comment by lukasgit** [comment]
I’m sorry guys. My partner is dead. It has been hard for me. Tomorrow I
will try my best to catch up with the backlog. But I could really use help
from any one of you. 🙏🏻❤️

**Comment by BetterB0y** [comment]
@lukasgit After this one app is not building.

/java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java:299: error: cannot find symbol
        cursor.close();
        ^
  symbol:   variable cursor
  location: class ContactsServicePlugin.BaseContactsServiceDelegate

**Comment by VladimirGradev** [comment]
> @lukasgit After this one app is not building.
> 
> /java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java:299: error: cannot find symbol cursor.close(); ^ symbol: variable cursor location: class ContactsServicePlugin.BaseContactsServiceDelegate

This was fixed long time ago, we are no longer using contacts_service as a dependency. Please get a fresh main.

**Comment by VladimirGradev** [comment]
> @lukasgit After this one app is not building.
> 
> /java/flutter/plugins/contactsservice/contactsservice/ContactsServicePlugin.java:299: error: cannot find symbol cursor.close(); ^ symbol: variable cursor location: class ContactsServicePlugin.BaseContactsServiceDelegate

Please get latest changes from main

**Comment by BetterB0y** [comment]
Its caused because cursor variable is not in { }.
Proper code should look like this:
```java
if (intent == null) {
    return true;
}

Cursor cursor = contentResolver.query(contactUri, null, null, null, null);
if (cursor.moveToFirst()) {
    String id = contactUri.getLastPathSegment();
    getContacts("openDeviceContactPicker", id, false, false, false, localizedLabels, this.result);
} else {
    Log.e(LOG_TAG, "onActivityResult - cursor.moveToFirst() returns false");
    finishWithResult(FORM_OPERATION_CANCELED);
}
cursor.close();
return true;
```

**Pull request merged**
