### PR TITLE
Remove redundant param name

### PR DESCRIPTION
**Pull request by VictorUvarov**
swift automatically uses named parameters

### CODE REVIEW

**Comment by FDuhen** [comment]
+1

**Comment by lukasgit** [comment]
Thanks for the PR!  I will review this weekend.

**Comment by ghenry** [comment]
Bump :)

**Comment by lukasgit** [comment]
I'm sorry for the delay.  I lost two very special people in my life.  I'm back now and will work on your PR over the weekend.  Thanks for your patience and understanding.

**Comment by imaNNeoFighT** [comment]
Thanks for contributing!

**Pull request merged**
