### PR TITLE
All fields support

### PR DESCRIPTION
**Pull request by jaypatel04**
These changes will support almost all fields like

Relations
Instant message address
Social profiles
Dates
Labels
Additionally, few other supports are provided like,

identifier is attached to all fields
additional method of getting only identifiers
additional method of getting only summary fields on list screen added

### CODE REVIEW

**Comment by gijsbeijer** [comment]
With 'Relations' you are referencing to merged contacts? If so, I need this 😁.

**Comment by lukasgit** [comment]
Thanks for the PR!  I will review this weekend.

**Comment by ghenry** [comment]
Any news?

**Comment by lukasgit** [comment]
I'm sorry for the delay.  I lost two very special people in my life.  I'm back now and will work on your PR over the weekend.  Thanks for your patience and understanding.

**Comment by ghenry** [comment]
Sorry for your loss Lukas.

**Comment by jaypatel04** [comment]
> I'm sorry for the delay. I lost two very special people in my life. I'm back now and will work on your PR over the weekend. Thanks for your patience and understanding.

Sorry to hear this

**Pull request closed without merging**
