### PR TITLE
minor fix for swift function

### PR DESCRIPTION
**Pull request by lidongze91**

### CODE REVIEW

**Comment by lidongze91** [comment]
@lukasgit  Hi, can you merge this? Thanks.

**Comment by lukasgit** [comment]
@mehmetf please stop merging directly into master branch.  I emailed you yesterday about this.

**PR's must go to staging branch**

**Comment by mehmetf** [comment]
I did not receive the email. I do apologize.

Is there a more extensive guide to contributing? I see : "If you want to contribute code please create a pull request under the staging branch." A series of git commands on how to do this would go a long way.

Do you have a process on when/how staging commits make it to master? We pull in master branch into our internal repo. The primary motivation for us to become contributors to this repo was to be able to quickly push fixes/features to it and consume them downstream. I would like to avoid any delays that staging -> master would introduce to this process as that would defeat the purpose. For instance, if you go on vacation and cannot review/merge to master for a couple of weeks.

Thanks for letting us know so we can be in compliance with your repo rules in the future.

**Comment by lukasgit** [comment]
The only requirement is to push PR's to staging first, then merge those changes with master.  Keeps everything clean and organized.

I'll look into a more extensive guide to contributing but right now my plate is incredibly full.  Many thanks for your help!

**Pull request merged**
