### PR TITLE
iOS Get All Contacts

### PR DESCRIPTION
**Pull request by Faiyyaz**
Hi,

I have changed some code for get all contacts as it was not fetching contacts from all containers(Keyword as per the contact framework of iOS) of contacts because of which the number of contacts returned where less or as i can say only limited to phonebook.

### CODE REVIEW

**Comment by lukasgit** [comment]
Thanks for the PR!  I will review this weekend.

**Comment by jaypatel04** [comment]
These changes will duplicate the iOS contacts. First I too made this change in my forked branch but I had to revert this as it will return duplicate list of contacts

**Comment by Faiyyaz** [comment]
But what if someone wants contact from all sources irrespective whether duplicate or not. And @jaypatel04 have you been able to filter out the duplicate contacts somehow?

**Comment by lukasgit** [comment]
I'm sorry for the delay.  I lost two very special people in my life.  I'm back now and will work on your PR over the weekend.  Thanks for your patience and understanding.

**Comment by jaypatel04** [comment]
> But what if someone wants contact from all sources irrespective whether duplicate or not. And @jaypatel04 have you been able to filter out the duplicate contacts somehow?

Yes, I implemented all containers fetch as per your solution and in the list just kept one check to prevent duplicates. It’s manual check at every insert in list 😯

**Pull request closed without merging**
