### PR TITLE
Fixed error #194

### PR DESCRIPTION
**Pull request by Faiyyazauxy**
Hello this PR fixes the error #194. This was happening if a user denied the permission permanently for the contacts. Also i have made the project androidx compatible too.

### CODE REVIEW

**Comment by brianschardt** [comment]
can we get this merged in?

**Comment by lukasgit** [comment]
@Faiyyazauxy @brianschardt please change your push branch to `lukasgit:staging` and I will merge. Thanks

**Comment by Faiyyazauxy** [comment]
@lukasgit I have changed the base branch to staging

**Comment by brianschardt** [comment]
@lukasgit thanks for the quick response, excited to have this merged in.

**Comment by lukasgit** [comment]
Thanks @Faiyyazauxy 

@brianschardt Done!

**Pull request merged**
