### PR TITLE
Added creating and editing contacts via device form

### PR DESCRIPTION
**Pull request by engylemure**
Considering the existence of native forms existing in IOS and Android, I tried to provide some methods for creating and editing contacts through them.

### CODE REVIEW

**Comment by lukasgit** [comment]
@engylemure thanks for your PR.  Two issues need to be resolved:

1. The build is failing with Travis CI.
2. Please submit your PR to the staging branch (not master).

Thanks!

**Comment by engylemure** [comment]
@lukasgit Sorry for the delay.
> @engylemure thanks for your PR. Two issues need to be resolved:
> 
> 1. The build is failing with Travis CI.
> 2. Please submit your PR to the staging branch (not master).
> 
> Thanks!

Solved these issues.
Thanks!

**Comment by lukasgit** [comment]
@engylemure my apologies for the late response!

Changes were made in PR #84 to migrate this plugin to android v2 embedding. Those changes affected a few lines of your PR code in ContactsServicePlugin.java.

Can you please update your code and let me know when the PR is ready? Thanks!

**Comment by engylemure** [comment]
> @engylemure my apologies for the late response!
> 
> Changes were made in PR #84 to migrate this plugin to android v2 embedding. Those changes affected a few lines of your PR code in ContactsServicePlugin.java.
> 
> Can you please update your code and let me know when the PR is ready? Thanks!

Sure, it is Ready.

**Comment by lukasgit** [comment]
Thank you @engylemure !

**Pull request merged**
