### PR TITLE
Migrate from jcenter() to mavenCentral()

### PR DESCRIPTION
**Pull request by eli1stark**

### CODE REVIEW

**Comment by alvarisi** [comment]
can we merge this @lukasgit ?
currently, the jcenter is down, and it's better if we can fix this on flutter_contacts. 
thank you

**Comment by BetterB0y** [comment]
Please @lukasgit. We need this merge for lib to work properly.

**Comment by lukasgit** [comment]
Ok I will look into this today.

**Comment by BetterB0y** [comment]
@lukasgit Any updates? i would really appreciate merge.

**Comment by BetterB0y** [comment]
@lukasgit Can you just click "Merge"?

**Comment by eli1stark** [comment]
> @lukasgit Can you just click "Merge"?

You can reference specific branch/commit in the `pubspec.yaml` as a workaround for now.

**Comment by lukasgit** [comment]
Yes, will do when I get home.

**Comment by BetterB0y** [comment]
@lukasgit Please merge and publish to pub.dev

**Comment by lukasgit** [comment]
I was out of town. Will merge and publish today. Thanks

**Comment by lukasgit** [comment]
Done!

**Comment by BetterB0y** [comment]
@lukasgit Thanks. Please publish it to pub.dev too.

**Comment by BetterB0y** [comment]
@lukasgit Can you publish it to pub.dev?

**Comment by BetterB0y** [comment]
@lukasgit Can you publish it to pub.dev?

**Pull request merged**
